<?php

/**
 * PixelManager CMS (Community Edition)
 * Copyright (C) 2016 PixelProduction (http://www.pixelproduction.de)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * Smarty plugin
 * -------------------------------------------------------------
 * File:     function.module.php
 * Type:     function
 * Name:     module
 * Purpose:  outputs the html code generated by a 
             Pixelmanager CMS module
 * -------------------------------------------------------------
 */

function smarty_function_module($params, Smarty_Internal_Template $template)
{
    $output = '';
    if (isset($params['id'])) {
        $module_id = $params['id'];
        if (FrontendModules::isModuleLoaded($module_id)) {
            $module = FrontendModules::getInstanceOf($module_id);
            $output = $module->output($params, $template);
            if ($output === null) {
                $output = '';
            }
        } else {
            Helpers::debugError('Smarty plugin function.module.php: frontend module with ID "' . $module_id . '" was not loaded.');
        }
    } else {
        Helpers::debugError('Smarty plugin function.module.php: parameter "id" is missing.');
    }
    return ($output);
}
